version: "3"
services:
  postgres:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cybergarden
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@da.ru
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - '5050:80'
